// <auto-generated />
namespace DotNetAppSqlDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecategorynamefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecategorynamefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301849328_update-category-name-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
